Repository scrum-gang/jobhub-chrome, pull requests merged in 2019-02, with the labels that each got.

#18 Fix/4 scraping
  src/ScrapingFunctions.re
Labels: bug

#22 feat: add stylized cv dropdown
  src/App.css
  src/JobApp.re
Labels: enhancement

#21 feat: implement posted date scrapper
  src/JobApp.re
  src/ScrapingFunctions.re
Labels: enhancement

#27 Test ScrapingFunctions & set up CI
  .travis.yml
  README.md
  __tests__/ScrapingFunctions_test.re
  bsconfig.json
  package-lock.json
  package.json
  src/ScrapingFunctions.re
Labels: CI/CD

#28 Feat/12 company scraper
  bsconfig.json
  data/business-names.json
  manifest.json
  package-lock.json
  package.json
  src/Constants.re
  src/JobApp.re
  src/ScrapingFunctions.re
  src/Services.re
  webpack.config.js
Labels: enhancement

#29 Feat/24 community
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: docs

#31 Feat/30 test scraping fns
  __tests__/ScrapingFunctions_test.re
  src/JobApp.re
  src/ScrapingFunctions.re
Labels: enhancement

#33 Feat/16 authentication
  manifest.json
  src/App.css
  src/App.re
  src/Login.re
  src/ScrapingInput.re
  src/Services.re
  src/Utilities.re
Labels: enhancement

#38 Feat/37 resume revision
  src/App.re
  src/Constants.re
  src/JobApp.re
  src/Services.re
  src/SyncStorage.re
Labels: enhancement

#34 Feat/19 store token
  manifest.json
  package-lock.json
  src/App.re
  src/Constants.re
  src/JobApp.re
  src/Login.re
  src/ScrapingFunctions.re
  src/Services.re
  src/SyncStorage.re
  src/Utilities.re
Labels: enhancement

#39 fix: load company names
  src/JobApp.re
Labels: bug
